name = "cms"
main = "src/index.ts"
compatibility_date = "2022-12-10"

[[kv_namespaces]]
binding = "kvCMS"
id = "..."
preview_id = "..."

[[r2_buckets]]
binding = "r2CMS"
bucket_name = "..."
preview_bucket_name = "..."

[[d1_databases]]
binding = "d1CMS"
database_name = "..."
database_id = "..."
preview_database_id = "..."